; ═══════════════════════════════════════════════════════════════════════════════
; KeyTracker.ahk - Feature 3: keystroke history in 1-minute snapshots
; ═══════════════════════════════════════════════════════════════════════════════
; A pass-through InputHook records every keystroke, attributes it to the
; currently focused window, and buffers it until the minute rolls over. Each
; flush writes one key_snapshot row containing several *views* of that minute:
;
;   raw_stream   Send()-compatible keystroke log: "hello{Enter}{Tab}world"
;   text_typed   the literal text after backspaces are applied
;   strings      contiguous typed runs (>= 3 chars), one per line
;   sentences    sentence-shaped runs (>= 3 words, terminated or line-final)
;   code_snips   runs that look like code rather than prose
;   hotkeys      space-separated combos: "^c ^v !{Tab}"
;   clips        clipboard contents copied during the minute
;
; Synthetic input generated by this script's own macros is excluded (InputHook
; option I1), so replaying a workflow never pollutes the history.
;
; PRIVACY: this is a keystroke logger writing plaintext to a local database.
; It is OFF by default, has an explicit on/off control, honours a per-window
; exclusion list (KeyTrack_ExcludeWindow) and skips password-style fields when
; the window name matches KEYTRACK_SENSITIVE_PATTERN.
; ═══════════════════════════════════════════════════════════════════════════════
; ─── Configuration ───────────────────────────────────────────────────────────
global g_KeyTrackOn := false
global g_KeyTrackHook := ""
global g_KeyTrackClipOn := false
global g_KeyTrackMaxStream := 20000     ; Restart the hook past this many chars
global g_KeyTrackPauseMs := 1500        ; Gap that ends a "string" run
global g_KeyTrackExclude := []          ; Window-name substrings never recorded
; Window names matching this are skipped entirely (credential prompts etc).
global KEYTRACK_SENSITIVE_PATTERN := "i)(password|passphrase|credential|sign in|log ?in|bitwarden|lastpass|keepass|1password)"
; ─── Bucket state ────────────────────────────────────────────────────────────
global g_KeyBucket := ""
global g_KeyLastCharTick := 0
; ═══════════════════════════════════════════════════════════════════════════════
; PUBLIC CONTROL
; ═══════════════════════════════════════════════════════════════════════════════
KeyTrack_Start(withClipboard := true) {
    global g_KeyTrackOn, g_KeyTrackHook, g_KeyTrackClipOn
    if !TrackDB_Ready() {
        if !TrackDB_Init()
            return false
    }
    if g_KeyTrackOn
        return true
    try {
        ; V   - visible: keystrokes still reach the focused window
        ; I1  - ignore input synthesised by this script's own Send calls
        ih := InputHook("I1 V")
        ih.VisibleText := true
        ih.VisibleNonText := true
        ih.NotifyNonText := true
        ih.KeyOpt("{All}", "N")          ; notify OnKeyDown for every key
        ih.OnChar := KeyTrack_OnChar
        ih.OnKeyDown := KeyTrack_OnKeyDown
        ih.Start()
        g_KeyTrackHook := ih
    } catch as err {
        TrackLogError("KeyTrack_Start", err)
        return false
    }
    if withClipboard {
        try {
            OnClipboardChange(KeyTrack_OnClipChange, 1)
            g_KeyTrackClipOn := true
        } catch as err {
            TrackLogError("KeyTrack_Start(clipboard)", err)
        }
    }
    g_KeyTrackOn := true
    return true
}
KeyTrack_Stop() {
    global g_KeyTrackOn, g_KeyTrackHook, g_KeyTrackClipOn
    if !g_KeyTrackOn
        return
    if IsObject(g_KeyTrackHook) {
        try g_KeyTrackHook.Stop()
    }
    g_KeyTrackHook := ""
    if g_KeyTrackClipOn {
        try OnClipboardChange(KeyTrack_OnClipChange, 0)
        g_KeyTrackClipOn := false
    }
    KeyTrack_FlushBucket()
    g_KeyTrackOn := false
}
KeyTrack_Toggle() {
    global g_KeyTrackOn
    if g_KeyTrackOn
        KeyTrack_Stop()
    else
        KeyTrack_Start()
    return g_KeyTrackOn
}
KeyTrack_IsOn() {
    global g_KeyTrackOn
    return g_KeyTrackOn
}
; Never record keystrokes for windows whose name contains `substring`.
KeyTrack_ExcludeWindow(substring) {
    global g_KeyTrackExclude
    if (substring = "" || TrackArrayHas(g_KeyTrackExclude, substring))
        return false
    g_KeyTrackExclude.Push(substring)
    TrackDB_MetaSet("keytrack_exclude", TrackArrayJoin(g_KeyTrackExclude, "|"))
    return true
}
KeyTrack_LoadExclusions() {
    global g_KeyTrackExclude
    raw := TrackDB_MetaGet("keytrack_exclude", "")
    g_KeyTrackExclude := (raw = "") ? [] : StrSplit(raw, "|")
    return g_KeyTrackExclude
}
; True when the given window name must not be recorded.
KeyTrack_IsExcluded(winName) {
    global g_KeyTrackExclude, KEYTRACK_SENSITIVE_PATTERN
    if (winName = "")
        return true
    if RegExMatch(winName, KEYTRACK_SENSITIVE_PATTERN)
        return true
    for frag in g_KeyTrackExclude {
        if (frag != "" && InStr(winName, frag))
            return true
    }
    return false
}
; Called by the window tracker when focus moves.
KeyTrack_OnWindowChange(ctx) {
    global g_KeyTrackOn
    if !g_KeyTrackOn
        return
    KeyTrack_FlushBucket()
}
; ═══════════════════════════════════════════════════════════════════════════════
; BUCKETS
; ═══════════════════════════════════════════════════════════════════════════════
KeyTrack_NewBucket(ctx) {
    return Map(
        "win_id", ctx["win_id"],
        "app_id", ctx["app_id"],
        "win_name", ctx["name"],
        "minute_key", TrackMinuteKey(),
        "start_ts", TrackTS(),
        "start_tick", A_TickCount,
        "keystrokes", 0,
        "stream", [],        ; Send()-compatible tokens
        "text", [],          ; literal characters, backspace-aware
        "runs", [],          ; completed contiguous typing runs
        "hotkeys", [],
        "clips", []
    )
}
KeyTrack_EnsureBucket() {
    global g_KeyBucket
    ctx := TrackCtx_Get(750)
    if !ctx["win_id"]
        return ""
    if KeyTrack_IsExcluded(ctx["name"])
        return ""
    minuteKey := TrackMinuteKey()
    if IsObject(g_KeyBucket) {
        if (g_KeyBucket["win_id"] = ctx["win_id"] && g_KeyBucket["minute_key"] = minuteKey)
            return g_KeyBucket
        KeyTrack_FlushBucket()
    }
    g_KeyBucket := KeyTrack_NewBucket(ctx)
    return g_KeyBucket
}
KeyTrack_FlushBucket() {
    global g_KeyBucket, g_KeyTrackHook, g_KeyTrackMaxStream
    if !IsObject(g_KeyBucket)
        return false
    b := g_KeyBucket
    g_KeyBucket := ""
    if (b["keystrokes"] = 0 && b["clips"].Length = 0)
        return false
    try {
        KeyTrack_CloseRun(b)
        text := KeyTrack_ApplyBackspaces(b["text"])
        classified := KeyTrack_Classify(b["runs"], text)
        elapsedMin := Max(0.05, (A_TickCount - b["start_tick"]) / 60000.0)
        wpm := Round((StrLen(text) / 5.0) / elapsedMin, 1)
        snap := Map(
            "win_id", b["win_id"],
            "app_id", b["app_id"],
            "minute_key", b["minute_key"],
            "start_ts", b["start_ts"],
            "end_ts", TrackTS(),
            "keystrokes", b["keystrokes"],
            "raw_stream", TrackArrayJoin(b["stream"], ""),
            "text_typed", text,
            "hotkeys", TrackArrayJoin(b["hotkeys"], " "),
            "strings", classified["strings"],
            "sentences", classified["sentences"],
            "code_snips", classified["code"],
            "clips", TrackArrayJoin(b["clips"], "`n"),
            "wpm", wpm
        )
        TrackDB_AddKeySnapshot(snap)
        ; Per-window hotkey frequency, for "what does this user actually use".
        counts := Map()
        for combo in b["hotkeys"]
            counts[combo] := counts.Has(combo) ? counts[combo] + 1 : 1
        for combo, n in counts
            TrackDB_BumpHotkey(b["win_id"], b["app_id"], combo, n)
    } catch as err {
        TrackLogError("KeyTrack_FlushBucket", err)
        return false
    }
    ; Keep the InputHook's internal buffer from growing without bound.
    if IsObject(g_KeyTrackHook) {
        try {
            if (StrLen(g_KeyTrackHook.Input) > g_KeyTrackMaxStream) {
                g_KeyTrackHook.Stop()
                g_KeyTrackHook.Start()
            }
        }
    }
    return true
}
; ═══════════════════════════════════════════════════════════════════════════════
; CAPTURE CALLBACKS
; ═══════════════════════════════════════════════════════════════════════════════
; Printable characters arrive here already translated by the keyboard layout.
KeyTrack_OnChar(ih, char) {
    global g_KeyLastCharTick, g_KeyTrackPauseMs
    ; A modified keystroke is a command, not text - OnKeyDown logs it instead.
    if (GetKeyState("Control", "P") || GetKeyState("Alt", "P") || GetKeyState("LWin", "P")
        || GetKeyState("RWin", "P"))
        return
    b := KeyTrack_EnsureBucket()
    if !IsObject(b)
        return
    ; A long pause ends the current run, the same way a click or Enter would.
    now := A_TickCount
    if (g_KeyLastCharTick && (now - g_KeyLastCharTick) > g_KeyTrackPauseMs)
        KeyTrack_CloseRun(b)
    g_KeyLastCharTick := now
    b["keystrokes"] := b["keystrokes"] + 1
    b["stream"].Push(KeyTrack_EscapeForSend(char))
    b["text"].Push(char)
}
; Non-text keys: navigation, editing, function keys and modifier combos.
KeyTrack_OnKeyDown(ih, vk, sc) {
    keyName := ""
    try keyName := GetKeyName(Format("vk{:02X}sc{:03X}", vk, sc))
    if (keyName = "")
        return
    ; Modifier keys themselves are noise; they show up inside combos.
    if TrackArrayHas(["LControl", "RControl", "LShift", "RShift", "LAlt", "RAlt"
                    , "LWin", "RWin", "Control", "Shift", "Alt"], keyName)
        return
    b := KeyTrack_EnsureBucket()
    if !IsObject(b)
        return
    ctrl := GetKeyState("Control", "P")
    alt := GetKeyState("Alt", "P")
    win := GetKeyState("LWin", "P") || GetKeyState("RWin", "P")
    shift := GetKeyState("Shift", "P")
    b["keystrokes"] := b["keystrokes"] + 1
    ; ─── Modified keystroke: record as a hotkey combo ────────────────────────
    if (ctrl || alt || win) {
        combo := (ctrl ? "^" : "") . (alt ? "!" : "") . (shift ? "+" : "") . (win ? "#" : "")
        combo .= (StrLen(keyName) = 1) ? StrLower(keyName) : "{" . keyName . "}"
        b["hotkeys"].Push(combo)
        b["stream"].Push(combo)
        KeyTrack_CloseRun(b)      ; a command breaks the typing run
        return
    }
    ; ─── Editing / navigation keys ───────────────────────────────────────────
    switch keyName {
        case "Backspace":
            b["stream"].Push("{BS}")
            b["text"].Push("`b")      ; sentinel consumed by ApplyBackspaces
            return
        case "Enter", "NumpadEnter":
            b["stream"].Push("{Enter}")
            b["text"].Push("`n")
            KeyTrack_CloseRun(b)
            return
        case "Tab":
            b["stream"].Push("{Tab}")
            b["text"].Push("`t")
            KeyTrack_CloseRun(b)
            return
        case "Space":
            ; Already captured by OnChar as " "; do not double count.
            b["keystrokes"] := b["keystrokes"] - 1
            return
    }
    ; Everything else is logged verbatim and ends the current run.
    if (StrLen(keyName) > 1) {
        b["stream"].Push("{" . keyName . "}")
        KeyTrack_CloseRun(b)
    }
}
; Clipboard captures ride along with the keystroke history: a paste is only
; meaningful next to what was on the clipboard at the time.
KeyTrack_OnClipChange(dataType) {
    global g_KeyTrackOn
    if (!g_KeyTrackOn || dataType != 1)      ; 1 = plain text
        return
    content := ""
    try content := A_Clipboard
    if (content = "" || StrLen(content) > 100000)
        return
    ctx := TrackCtx_Get(1500)
    if KeyTrack_IsExcluded(ctx["name"])
        return
    try {
        TrackDB_AddClip(ctx["win_id"], ctx["app_id"], content, KeyTrack_ClipKind(content))
    } catch as err {
        TrackLogError("KeyTrack_OnClipChange", err)
        return
    }
    b := KeyTrack_EnsureBucket()
    if IsObject(b)
        b["clips"].Push(TrackEllipsis(content, 500))
}
; Rough content type for a clipboard entry.
KeyTrack_ClipKind(text) {
    t := Trim(text)
    if RegExMatch(t, "i)^https?://")
        return "url"
    if RegExMatch(t, "^[\w\.\-]+@[\w\.\-]+\.\w+$")
        return "email"
    if RegExMatch(t, "^[A-Za-z]:\\|^\\\\")
        return "path"
    if (KeyTrack_LooksLikeCode(t))
        return "code"
    if RegExMatch(t, "^-?[\d,\.]+$")
        return "number"
    return "text"
}
; ═══════════════════════════════════════════════════════════════════════════════
; RUNS AND CLASSIFICATION
; ═══════════════════════════════════════════════════════════════════════════════
; Close the current contiguous typing run and file it under "runs".
KeyTrack_CloseRun(b) {
    if !IsObject(b)
        return
    text := KeyTrack_ApplyBackspaces(b["text"])
    if (Trim(text) != "")
        b["runs"].Push(text)
    b["text"] := []
}
; Escape a literal character so raw_stream stays Send()-compatible.
KeyTrack_EscapeForSend(char) {
    switch char {
        case "{": return "{{}"
        case "}": return "{}}"
        case "^": return "{^}"
        case "!": return "{!}"
        case "+": return "{+}"
        case "#": return "{#}"
    }
    return char
}
; Collapse the backspace sentinels recorded by OnKeyDown.
KeyTrack_ApplyBackspaces(chars) {
    out := []
    for c in chars {
        if (c = "`b") {
            if out.Length
                out.Pop()
            continue
        }
        out.Push(c)
    }
    return TrackArrayJoin(out, "")
}
; Split the minute's typing into strings / sentences / code snippets.
KeyTrack_Classify(runs, fullText) {
    strings := []
    sentences := []
    code := []
    for run in runs {
        clean := Trim(run, " `t`r`n")
        if (StrLen(clean) < 3)
            continue
        strings.Push(clean)
        if KeyTrack_LooksLikeCode(clean) {
            code.Push(clean)
            continue
        }
        ; Sentence-shaped: at least three words. Split on terminators so a run
        ; containing several sentences yields several entries.
        for piece in KeyTrack_SplitSentences(clean) {
            words := StrSplit(Trim(piece), " ")
            realWords := 0
            for w in words {
                if (Trim(w) != "")
                    realWords++
            }
            if (realWords >= 3)
                sentences.Push(Trim(piece))
        }
    }
    return Map(
        "strings", TrackArrayJoin(strings, "`n"),
        "sentences", TrackArrayJoin(sentences, "`n"),
        "code", TrackArrayJoin(code, "`n")
    )
}
KeyTrack_SplitSentences(text) {
    ; Break after . ! ? when followed by whitespace or end of string.
    marked := RegExReplace(text, "([\.\!\?])(\s+|$)", "$1`n")
    out := []
    for line in StrSplit(marked, "`n") {
        if (Trim(line) != "")
            out.Push(line)
    }
    return out
}
; Heuristic code detector: structural tokens plus symbol density.
KeyTrack_LooksLikeCode(text) {
    if (StrLen(text) < 4)
        return false
    ; Strong structural signals from common languages, shells and SQL.
    if RegExMatch(text, "i)(^|\s)(function|def|class|import|from|return|const|let|var"
                      . "|public|private|static|void|struct|interface|namespace"
                      . "|select\s|insert\s+into|update\s|delete\s+from|create\s+table)(\s|\()")
        return true
    if RegExMatch(text, "(:=|=>|->|::|\+\+|--|!==|===|&&|\|\||</|/>|#include|#!/)")
        return true
    if RegExMatch(text, "\w+\s*\([^)]*\)\s*[{;]")
        return true
    if RegExMatch(text, "^\s*[\}\{\)\]]")
        return true
    ; Symbol density: prose rarely exceeds ~20% punctuation.
    symbols := 0
    total := 0
    Loop Parse, text {
        c := A_LoopField
        if (c = " ")
            continue
        total++
        if RegExMatch(c, "[\{\}\(\)\[\]<>;=+\-*/\\|&^%$#@~`_]")
            symbols++
    }
    if (total >= 8 && (symbols / total) > 0.28)
        return true
    return false
}
; ═══════════════════════════════════════════════════════════════════════════════
; QUERIES
; ═══════════════════════════════════════════════════════════════════════════════
KeyTrack_Snapshots(winId := 0, limit := 200) {
    db := TrackDB()
    if !db
        return []
    if winId {
        return db.Query("SELECT * FROM key_snapshot WHERE win_id=? "
                      . "ORDER BY minute_key DESC LIMIT ?", winId, limit)
    }
    return db.Query("SELECT k.*, w.name AS win_name FROM key_snapshot k "
                  . "JOIN win w ON w.id=k.win_id ORDER BY k.minute_key DESC LIMIT ?", limit)
}
KeyTrack_Snapshot(snapId) {
    db := TrackDB()
    if !db
        return Map()
    return db.QueryRow("SELECT k.*, w.name AS win_name FROM key_snapshot k "
                     . "JOIN win w ON w.id=k.win_id WHERE k.id=?", snapId)
}
KeyTrack_TopHotkeys(winId := 0, limit := 100) {
    db := TrackDB()
    if !db
        return []
    if winId {
        return db.Query("SELECT combo, count, last_ts FROM hotkey_stat WHERE win_id=? "
                      . "ORDER BY count DESC LIMIT ?", winId, limit)
    }
}
; ═══════════════════════════════════════════════════════════════════════════════
; DASHBOARD COMPATIBILITY
; ═══════════════════════════════════════════════════════════════════════════════
; The Tracking tab calls these; they live here so the dashboard and this module
; stay decoupled from each other's internals.

; One-line description of what the key tracker is doing right now.
KeyTrack_StatusLine() {
    global g_KeyTrackOn, g_KeyBucket, g_KeyTrackExclude
    if !g_KeyTrackOn
        return "Key tracking: OFF"
    if !IsObject(g_KeyBucket)
        return "Key tracking: ON (waiting for keystrokes)"
    return "Key tracking: " . g_KeyBucket["keystrokes"] . " keys, "
         . g_KeyBucket["hotkeys"].Length . " hotkeys this minute"
         . (g_KeyTrackExclude.Length ? "  |  " . g_KeyTrackExclude.Length . " excluded window(s)" : "")
}

; Recent clipboard captures, newest first (optionally for one window).
KeyTrack_RecentClips(limit := 200, winId := 0) {
    db := TrackDB()
    if !db
        return []
    if winId {
        return db.Query("SELECT c.*, w.name AS win_name FROM clip_history c "
                      . "LEFT JOIN win w ON w.id=c.win_id WHERE c.win_id=? "
                      . "ORDER BY c.id DESC LIMIT ?", winId, limit)
    }
    return db.Query("SELECT c.*, w.name AS win_name FROM clip_history c "
                  . "LEFT JOIN win w ON w.id=c.win_id ORDER BY c.id DESC LIMIT ?", limit)
}

; The exclusion list, for display/editing in the UI.
KeyTrack_Exclusions() {
    global g_KeyTrackExclude
    return g_KeyTrackExclude
}

; Remove a previously excluded window-name fragment.
KeyTrack_UnexcludeWindow(substring) {
    global g_KeyTrackExclude
    for i, frag in g_KeyTrackExclude {
        if (frag = substring) {
            g_KeyTrackExclude.RemoveAt(i)
            TrackDB_MetaSet("keytrack_exclude", TrackArrayJoin(g_KeyTrackExclude, "|"))
            return true
        }
    }
    return false
}
